name: PowerBlocks Docker Image Build
run-name: Build Docker images for PowerBlocks
on:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        arch: [ { 'tag': 'amd64', 'runner': 'ubuntu-latest' }, { 'tag': 'aarch64', 'runner': 'ubuntu-24.04-arm' } ]
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}:${{ matrix.arch.tag }}
      - name: Docker build
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
        
  imagetools:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}:latest
          labels:
      - name: Create manifest list
        uses: kphrx/docker-buildx-imagetools-action@v0.1.0
        with:
          sources: |
            ghcr.io/${{ github.repository }}:amd64
            ghcr.io/${{ github.repository }}:aarch64
          tags: ${{ steps.meta.outputs.tags }}
      - name: Push docker image
        run: docker image push ${{ steps.meta.outputs.tags }}