name: PowerBlocks Docker Image Build
run-name: Build Docker images for PowerBlocks
on:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        arch: [ { 'tag': 'amd64', 'runner': 'ubuntu-latest' }, { 'tag': 'aarch64', 'runner': 'ubuntu-24.04-arm' } ]
    outputs:
      amd64_sha: ${{ steps.docker-output.outputs.amd64_sha }}
      aarch64_sha: ${{ steps.docker-output.outputs.aarch64_sha }}
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker build
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/Dockerfile
      - name: Tag output
        id: docker-output
        run: echo "${ARCH}_sha=${OUTPUT}" >> "$GITHUB_OUTPUT"
        env:
          OUTPUT: ${{ steps.docker-build.outputs.imageid }}
          ARCH: ${{ matrix.arch.tag }}
        
  imagetools:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Create manifest list
        uses: kphrx/docker-buildx-imagetools-action@v0.1.0
        with:
          sources: |
            ${{ needs.build-images.outputs.amd64_sha }}
            ${{ needs.build-images.outputs.aarch64_sha }}
          tags: ghcr.io/${{ github.repository }}:latest