name: PowerBlocks Docker Image Build
run-name: Build Docker images for PowerBlocks
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build-images:
    strategy:
      matrix:
        arch: [ { 'tag': 'amd64', 'runner': 'ubuntu-latest' }, { 'tag': 'arm64', 'runner': 'ubuntu-24.04-arm' } ]
        style: [ { 'tag': 'slim', 'llvm_extras': '', 'extra_installs': '' }, { 'tag': 'dev', 'llvm_extras': ';clang-tools-extra;lldb', 'extra_installs': 'install-clangd install-lldb install-lldb-dap' } ]
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: powerblocks
          tags: ${{ matrix.style.tag }}-${{ matrix.arch.tag }}
      
      - name: Docker build
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/Dockerfile
          build-args: |
            LLVM_EXTRAS=${{ matrix.style.llvm_extras }}
            EXTRA_INSTALLS=${{ matrix.style.extra_installs }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ matrix.style.tag }}-${{ matrix.arch.tag }}.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.style.tag }}-${{ matrix.arch.tag }}
          path: ${{ runner.temp }}/${{ matrix.style.tag }}-${{ matrix.arch.tag }}.tar
        
  imagetools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        style: [ 'slim', 'dev' ]
    needs: build-images
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download AMD64 image
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.style }}-amd64
          path: ${{ runner.temp }}
      - name: Download ARM64 image
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.style }}-arm64
          path: ${{ runner.temp }}

      - name: Load images
        run: |
          docker load --input ${{ runner.temp }}/${{ matrix.style }}-amd64.tar
          docker load --input ${{ runner.temp }}/${{ matrix.style }}-arm64.tar

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ matrix.style}}-latest
            ${{ matrix.style }}-${{ inputs.version }}

      - name: Create manifest list
        uses: kphrx/docker-buildx-imagetools-action@v0.1.0
        with:
          sources: |
            powerblocks:${{ matrix.style }}-amd64
            powerblocks:${{ matrix.style }}-arm64
          tags: ${{ steps.meta.outputs.tags }}